development:
  adapter: mongodb
  host: flame.mongohq.com
  port: 27067
  database: controle_horas
  user: kibiluzbad
  password: inferno1
test:
  adapter: sqlite3
  database: db/controleHoras_test.sqlite3
  pool: 5
  timeout: 5000
production:
  adapter: sqlite3
  database: db/production.sqlite3
  pool: 5
  timeout: 5000
migration:
  database: db/controleHoras_development.sqlite3
